### ISSUE TITLE
websockets support

### ISSUE THREAD

**Issue by rmrbest** [coreos/alb-ingress-controller#189]
I would like to know if we have support for websockets. Which steps to do it? Any annotations?

**Comment by tomhughesnice** [comment]
The AWS ALB supported websockets from the beginning. https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/

**Comment by rmrbest** [comment]
Yes, but when you have N replicas deployed, i've a problem, because i receive a 400 error handshake some times.

**Comment by rmrbest** [comment]
I fixed adding sessionAffinity on my service definition as ClientIP. 

It works now, without session id unknown message error in the polling requests.

**Comment by ricardohsd** [comment]
Hi @rmrbest I'm curious in how you fixed it. I've checked and ingress doesn't provide sessionAffinity option.

**Comment by sohan** [comment]
@ricardohsd you define sessionAffinity on your service's spec:

```
apiVersion: v1
kind: Service
metadata:
  ...
spec:
  type: NodePort
  sessionAffinity: ClientIP
```

**Comment by sohan** [comment]
Actually I'm also seeing handshake errors even with `sessionAffinity: ClientIP` when upgrading from polling to the websocket transport using socket.io. It seems I have to [enable stickiness in the ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#sticky-sessions). I get the handshake 400 error less frequently now, but it still happens now.

Would anyone have ideas for how to debug this? I'm not sure I understand why `sessionAffinity: ClientIP` is not enough and stickiness needs to be enabled at all. 

cc @rmrbest would you be able to share your exact set up and manifests? Thanks!

**Comment by vrathore18** [comment]
@sohan : are you able to solve the issue?? could someone provide the solution.

**Comment by sohan** [comment]
@vrathore18 I wasn't able to solve this issue. We worked around it instead by disabling the `polling` transport for socket.io. I.e. on our clients, we use:

```
const io = require('socket.io-client');
const socket = io(path, { transports: ['websocket'] });
```

I also removed the `sessionAffinity` setting from our service.

**Comment by M00nF1sh** [comment]
@sohan I have posted instructions on how to use websocket/socket.io in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1090, socket.io is not websocket
